### ISSUE TITLE
Lucene version incompatibility of Neo4j and ElasticSearch

### ISSUE THREAD

**Issue by KartikSinghal** [dbpedia/keyword-search#1]
Neo4j Uses Lucene version 3.6 and ElasticSearch uses 4.10.
These both versions are incompatible with each other

**Comment by rajnikanth-inbetween** [comment]
Hi, we are also facing this same issue ???

**Comment by KartikSinghal** [comment]
You can use either older version of Elastic search which uses lucene 3.6 (Elastic Search 0.20.x) or other option you can use SOLR.  
There is one more way where you can make a REST based API to exchange data between them. See here (http://neo4j.com/developer/elastic-search/), But it depends on how you want to use them together.
